'home/index':
    pagetitle: 'MeuMobi Corporate - Sua empresa na Web móvel em 3 minutos!'
    title: 'A versão mobile do seu portal pronta em instantes.'
    subtitle: 'Portais de notícias, portais corporativos e intranets de empresa.'
    features1_title: 'Painel de controle fácil de editar:'
    features2_title: 'Atualização automática de conteúdo:'
    features3_title: 'Compatível com mais de 6 mil celulares:'
    features4_title: 'Identidade visual do seu Portal:'
    features1_description: 'Criação de categorias, subcategorias e inserção de artigos e links externos;'
    features2_description: 'Todas as sessões do seu portal são atualizadas via RSS automaticamente;'
    features3_description: 'Tecnologia de renderização que possibilita que seu mobi site seja visualizado perfeitamente em mais de 6 mil aparelhos;'
    features4_description: 'Integração com Twitter, Facebook e Google Maps;'
'sites/finished':
    categories: 'Adicione as categorias do seu negocio ›'
