'home/index':
    pagetitle: 'MeuMobi Corporate - Sua empresa na Web móvel em 3 minutos!'
    title: 'A versão mobile do seu portal pronta em instantes.'
    subtitle: 'Portais de notícias, portais corporativos e intranets de empresa.'
'sites/finished':
    categories: 'Adicione as categorias do seu negocio ›'
