'home/index':
    pagetitle: 'MeuMobi - Mobile site for your business'
    title: 'The easiest way to create your company's mobile site'
    subtitle: 'It's simple and free!'

'sites/finished':
    categories: 'Add your business content ›'


