'home/index':
    pagetitle: 'MeuMobi Restaurant - Seu restaurante na Web móvel em 3 minutos!'
    title: 'Seu restaurante na palma da mão em menos de 3 minutos.'
    subtitle: 'MeuMobi Restaurant coloca o seu negócio na Internet móvel em instantes.'
'sites/finished':
    categories: 'Adicione o cardápio de seu restaurante ›'
