'home/index':
    pagetitle: 'MeuMobi Events - Mobile site for your event'
    title: 'Your event has a new location: the mobile phones of millions of people!'
    subtitle: 'Concerts, parties, movies, sporting events and more. It's simple and free!'

'sites/finished':
    categories: 'Add next events to your new mobi site ›'


