'home/index':
    pagetitle: 'MeuMobi Restaurant - Seu restaurante na Web móvel em 3 minutos!'
    title: 'Seu restaurante na palma da mão em menos de 3 minutos.'
    subtitle: 'MeuMobi Restaurant coloca o seu negócio na Internet móvel em instantes.'
    features1_title: 'Painel de controle fácil de editar:'
    features2_title: 'Atualização automática de conteúdo:'
    features3_title: 'Compatível com mais de 6 mil celulares:'
    features4_title: 'Integração com mídias sociais:'
    features1_description: 'Criação de eventos com descrição, programação, local,
    data, hora e outras informações;'
    features2_description: 'Todas as sessões do seu portal atualizadas via RSS automaticamente;'
    features3_description: 'Tecnologia de renderização que possibilita que seu mobi site seja visualizado perfeitamente em mais de 6 mil aparelhos;'
    features4_description: 'Integração com Twitter, Facebook e Google Maps;'
'sites/finished':
    categories: 'Adicione o cardápio de seu restaurante ›'
