'home/index':
    pagetitle: 'MeuMobi Corporate - Your company on the mobile web in a split second'
    title: 'The easiest way to create and deploy your company’s mobile website'
    subtitle: 'News and corporate website and enterprise intranets.'

'sites/finished':
    categories: 'Add your business content ›'