'home/index':
    pagetitle: 'Digital Marketing - Internet Marketing for Small Business.'
    title: 'The easiest way to create and deploy your company’s mobile website'
    subtitle: 'News and corporate website and enterprise intranets.'

'sites/finished':
    categories: 'Add your business content ›'
