'home/index':
    pagetitle: 'MeuMobi Restaurants - Your company in the web movel in 3 minutes'
    title: 'Your restaurant in the palm of your hand in less than 3 minutes.'
    subtitle: 'MeuMobi Restaurant puts your business on the mobile internet in seconds.'

'sites/finished':
    categories: 'Add the menu of your restaurant ›'
        
'Visual identity of your portal: ': 'Visual identity of your restaurant'
'Creation of categories, subcategories and insert of articles, products, events and external links;': 'Add your menu, starters, main dishes, etc. with details and photos'
