'home/index':
    pagetitle: 'MeuMobi Restaurants - Mobile site for your restaurant'
    title: 'The easiest way to create your restaurant's mobile site.'
    subtitle: 'It's simple and free!'

'sites/finished':
    categories: 'Add the menu of your restaurant ›'
        

